---
# Replace the fields below with relevant information.
# See https://www.mkdocs.org/user-guide/configuration/
# to learn more about the configuration options.
site_name: Ansible project template # FIX ME
site_url: https://ansible.readthedocs.io/PROJECTNAME # FIX ME
repo_url: https://github.com/ansible-community/project-template # FIX ME
edit_uri: blob/main/docs/
docs_dir: docs
strict: true

theme:
  name: 'ansible'

nav:
  - Home: 'index.md'
